# Copyright 2019 MNF (illvart). All Rights Reserved.
#
# Creative Commons Attribution 4.0 International License
# https://creativecommons.org/licenses/by/4.0/
#
# GitHub: https://github.com/illvart

plugins:
    - prettier

extends:
    - eslint:recommended
    - google

rules:
    no-console: off
    quotes: [error, double]
    comma-dangle: [error, never]
    indent: [error, 2]
    no-unused-vars: warn
    no-var: off # use var just for browser
    spaced-comment: off

env:
    browser: true
    node: true
    es6: true
    mocha: true

parserOptions:
    ecmaVersion: 2017
    sourceType: module

globals:
    importScripts: false
    workbox: false
