plugins:
    - stylelint-order
    - stylelint-scss

rules:
    order/order: [[custom-properties, declarations]]
    order/properties-alphabetical-order: true

    scss/at-else-closing-brace-newline-after: always-last-in-chain
    scss/at-else-closing-brace-space-after: always-intermediate
    scss/at-else-empty-line-before: never
    scss/at-if-closing-brace-newline-after: always-last-in-chain
    scss/at-if-closing-brace-space-after: always-intermediate
    scss/at-rule-no-unknown: true
    scss/no-duplicate-dollar-variables: [true, {ignoreInside: [at-rule]}]

    at-rule-name-newline-after: always-multi-line
    at-rule-name-space-after: always-single-line
    at-rule-no-unknown: true
    at-rule-no-vendor-prefix: true
    at-rule-semicolon-newline-after: always

    color-hex-case: lower
    color-hex-length: long
    color-no-invalid-hex: true

    comment-empty-line-before: [always, {except: [first-nested], ignore: [stylelint-commands]}]
    comment-no-empty: true
    comment-whitespace-inside: always

    custom-property-empty-line-before: never

    declaration-bang-space-after: never
    declaration-bang-space-before: always
    declaration-block-semicolon-newline-after: always
    declaration-block-semicolon-newline-before: never-multi-line
    declaration-block-semicolon-space-after: always-single-line
    declaration-block-semicolon-space-before: never
    declaration-block-trailing-semicolon: always
    declaration-colon-newline-after: always-multi-line
    declaration-colon-space-after: always-single-line
    declaration-colon-space-before: never
    declaration-empty-line-before: never

    font-family-name-quotes: always-where-recommended
    font-family-no-duplicate-names: true

    function-calc-no-invalid: true
    function-comma-space-before: never
    function-max-empty-lines: 0
    function-name-case: lower
    function-parentheses-newline-inside: never-multi-line
    function-parentheses-space-inside: never
    function-url-quotes: [always, {except: [empty]}]
    function-whitespace-after: always

    indentation: 2
    max-empty-lines: 1

    media-feature-colon-space-after: always
    media-feature-colon-space-before: never
    media-feature-name-case: lower
    media-feature-name-no-unknown: true
    media-feature-name-no-vendor-prefix: true
    media-feature-parentheses-space-inside: never
    media-feature-range-operator-space-after: always
    media-feature-range-operator-space-before: always
    media-query-list-comma-newline-after: always-multi-line
    media-query-list-comma-space-after: always-single-line
    media-query-list-comma-space-before: never

    no-duplicate-at-import-rules: true
    no-duplicate-selectors: true
    no-empty-source: true
    no-extra-semicolons: true
    no-unknown-animations: true

    number-leading-zero: never
    number-no-trailing-zeros: true

    property-case: lower
    property-no-unknown: true
    property-no-vendor-prefix: true

    rule-empty-line-before: [always-multi-line, {except: [first-nested], ignore: [after-comment]}]

    selector-attribute-operator-space-after: never
    selector-attribute-operator-space-before: never
    selector-attribute-quotes: always
    selector-combinator-space-after: always
    selector-combinator-space-before: always
    selector-descendant-combinator-no-non-space: true
    selector-list-comma-newline-after: always
    selector-list-comma-space-before: always-single-line
    selector-max-empty-lines: 0
    selector-no-vendor-prefix: true
    selector-pseudo-class-case: lower
    selector-pseudo-class-no-unknown: true
    selector-pseudo-class-parentheses-space-inside: never
    selector-pseudo-element-case: lower
    selector-pseudo-element-colon-notation: double
    selector-pseudo-element-no-unknown: true
    selector-type-case: lower
    selector-type-no-unknown: true

    shorthand-property-no-redundant-values: true

    string-no-newline: true
    string-quotes: double

    unit-case: lower
    unit-no-unknown: true
    unit-whitelist: [px, em, rem, vh, vw, "%", s, deg, cm, mm, in, pt, pc, ch, vmin, vmax]

    value-keyword-case: lower
    value-list-comma-space-after: always
    value-list-comma-space-before: never
    value-list-max-empty-lines: 0
    value-no-vendor-prefix: true
