[build]
  publish = "dist"
  command = "gulp default"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000"
    Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
    Content-Security-Policy = "report-uri https://illvart.report-uri.com/r/d/ct/reportOnly"
    Expect-CT = """
      max-age=0, report-uri="https://illvart.report-uri.com/r/d/ct/reportOnly"
    """

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "no-cache"
    X-UA-Compatible = "IE=Edge"

[[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Accept-Encoding = "gzip, deflate, br"
    Cache-Control = "max-age=31536000, immutable"

    [[headers]]
      for = "/assets/css/*.min.css"
      [headers.values]
        Content-Type = "text/css; charset=utf-8"
        Accept-Encoding = "gzip, deflate, br"
        Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Accept-Encoding = "gzip, deflate, br"
    Cache-Control = "max-age=31536000, immutable"

    [[headers]]
      for = "*.min.js"
      [headers.values]
        Content-Type = "text/javascript; charset=utf-8"
        Accept-Encoding = "gzip, deflate, br"
        Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"
    Accept-Encoding = "gzip, deflate, br"
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/assets/img/*.jpeg"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/assets/img/*.jpg"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/assets/img/*.png"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/assets/img/*.gif"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/assets/img/*.svg"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/assets/img/*.ico"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "/assets/img/*.webp"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

# Specify Brotli-encoded assets
[[headers]]
  for = "*.html.br"
  [headers.values]
    Content-Type = "text/html; .br"
    Accept-Encoding = "br"

[[headers]]
  for = "/assets/css/*.css.br"
  [headers.values]
    Content-Type = "text/css; .br"
    Accept-Encoding = "br"

    [[headers]]
      for = "/assets/css/*.min.css.br"
      [headers.values]
        Content-Type = "text/css; .br"
        Accept-Encoding = "br"

[[headers]]
  for = "*.js.br"
  [headers.values]
    Content-Type = "text/javascript; .br"
    Accept-Encoding = "br"

    [[headers]]
      for = "*.min.js.br"
      [headers.values]
        Content-Type = "text/javascript; .br"
        Accept-Encoding = "br"
