# Copyright 2019 MNF (illvart)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[build]
  publish = "dist"
  command = "yarn build" # or gulp default

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000"
    Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
    Content-Security-Policy = "report-uri https://illvart.report-uri.com/r/d/ct/reportOnly"
    Expect-CT = """
      max-age=0, report-uri="https://illvart.report-uri.com/r/d/ct/reportOnly"
    """

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "no-cache"
    X-UA-Compatible = "IE=Edge"

[[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

    [[headers]]
      for = "/assets/css/*.min.css"
      [headers.values]
        Content-Type = "text/css; charset=utf-8"
        Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

    [[headers]]
      for = "*.min.js"
      [headers.values]
        Content-Type = "text/javascript; charset=utf-8"
        Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# cache all images on assets/img
[[headers]]
  for = "/assets/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# cache all fonts on assets/fonts
[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
